### ISSUE TITLE
Зря ты так

### ISSUE THREAD

**Issue by cymon4380** [TerminalPR0/hiprotect#1]
Ну, рассказывай, какого хуя ты отобрал у меня 5к, слив исходник?

**Comment by youp1xxx** [comment]
эт пиздец...

**Comment by cymon4380** [comment]
сука, уже форкнули

**Comment by ArtemBay** [comment]
это очень плохо с твоей стороны

**Comment by ArtemBay** [comment]
> сука, уже форкнули

мдаааа.. треш как говорят восьмиклассницы

**Comment by TerminalPR0** [comment]
вы забыли первое правило интернета, и это уже не моя вина
а я напомню вам:
> Никогда и никому не доверяй в интернете, даже самым доверчивым.
